name: App Workflow

on:
  push:
    branches: [master]
  pull_request:
    branches:
      - "*"

jobs:
  build:
    name: App Workflow ${{ github.sha }}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run tests
        run: yarn test:ci

      - name: Run build
        run: yarn build
